name: "Tabnine PR review agent"

on:
  pull_request:
    branches:
      - main
        
permissions:
  contents: read
  pull-requests: write

jobs:
  review_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Review PR
        uses: codota/tabnine-pr-agent@v1
        continue-on-error: true
        with:
          PAT: ${{ secrets.COACHING_PAT }}
          ref: origin/${{ github.head_ref }}
          base_ref: origin/${{ github.base_ref }}
          path_to_repo: ${{ github.workspace }}
          repository_owner: ${{ github.repository_owner }}
          repository_name: ${{ github.event.repository.name }}
          pull_request_id: ${{ github.event.pull_request.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
